name: shop
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  conditional_builder_null_safety: ^0.0.6
  flutter_bloc: ^8.0.0
  dio: ^4.0.4
  shared_preferences: ^2.0.11
  hexcolor: ^2.0.5
  flutter_page_view_indicator: ^0.0.5
  fluttertoast: ^8.0.8
  carousel_slider: ^4.0.0
  splash_screen_view: ^3.0.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_launcher_icons_maker: ^0.10.2

flutter_icons:
  android: true
  ios: true
  macos: true
  windows: true
  web: true
  image_path: "assets/images/app_icon.png"


  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/

  